name: Test and Build Docker

on:
  push:
    branches:
      - main

jobs:
  extract-version:
    name: Extract Version from Git Tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract Version from Git Tag
        id: vars
        run: |
          VERSION=$(git describe --tags --abbrev=0 || echo "latest")
          echo "version=${VERSION}" >> $GITHUB_ENV
          echo "::set-output name=version::${VERSION}"

      - name: Debug Extracted Version
        run: echo "Extracted version ${{ steps.vars.outputs.version }}"

  test:
    name: Run Unit Tests
    needs: extract-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r src/requirements.txt

      - name: Run Unit Tests
        run: |
          source venv/bin/activate
          python -m unittest discover src

  build:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Validate Docker Tag
        run: |
          if [ -z "${{ needs.extract-version.outputs.version }}" ]; then
            echo "Version is not set, using fallback tag 'latest'."
            echo "fallback_version=latest" >> $GITHUB_ENV
          else
            echo "fallback_version=${{ needs.extract-version.outputs.version }}" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64 #
          tags: |
            giacomoalonzi/rehauneasmart_2_0_gateway:${{ env.fallback_version }}
            giacomoalonzi/rehauneasmart_2_0_gateway:latest
