name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Sostituisci con il branch che preferisci monitorare

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64
          tags: giacomoalonzi/rehauneasmart_2_0_gateway:latest

      - name: Post build cleanup
        run: docker system prune -f
